inherit_mode:
  merge:
    - Include

AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  Include:
    - .buildkite/danger/**/*
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile
    - Podfile
    - Rakefile

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 180

Naming/FileName:
  Exclude:
    - .buildkite/danger/Dangerfile
