steps:
  - label: "Start Code Freeze"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    env:
      # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
      IMAGE_ID: xcode-15.1
    command: |
      .buildkite/commands/configure-environment.sh

      # Expand this group to surface the information.
      echo '+++ :cocoapods: Outdated Pods'
      .buildkite/commands/log-outdated-pods.sh
